export const categories = [
  { slug: "t-shirts", title: "T-Shirts", image: "/studio-back-print-t-shirt.png", description: "Essential tees for every occasion" },
  { slug: "hoodies", title: "Hoodies", image: "/minimal-hoodie-back-print.png", description: "Cozy hoodies perfect for layering" },
  { slug: "cropped-tees", title: "Cropped Tees", image: "/cropped-tee-neutral-studio.png", description: "Modern cropped tees with contemporary silhouettes" },
  { slug: "sweatshirts", title: "Sweatshirts", image: "/minimal-sweatshirt-neutral.png", description: "Versatile sweatshirts for casual style" },
  { slug: "bottoms", title: "Bottoms", image: "/bottoms.png", description: "Essential bottoms for every wardrobe" },
  { slug: "outerwear", title: "Outerwear", image: "/overshirt.png", description: "Layered pieces for style and comfort" },
  { slug: "accessories", title: "Accessories", image: "/baseball-cap-neutral.png", description: "Complete your look with our curated accessories" },
]

export const products = [
  {
    slug: "heavyweight-classic-tee",
    name: "Heavyweight Classic Tee",
    category: "TEE",
    price: 28.0,
    collection: "t-shirts",
    image: "/basic-black-tee-back-print.png",
    badge: "Bestseller"
  },
  {
    slug: "oversized-graphic-hoodie",
    name: "Oversized Graphic Hoodie",
    category: "HOODIE",
    price: 58.0,
    collection: "hoodies",
    image: "/minimal-hoodie-back-print.png",
    badge: "New"
  },
  {
    slug: "crewneck-sweatshirt",
    name: "Crewneck Sweatshirt",
    category: "SWEATSHIRT",
    price: 48.0,
    collection: "sweatshirts",
    image: "/minimal-sweatshirt-neutral.png",
  },
  {
    slug: "boxy-cropped-tee",
    name: "Boxy Cropped Tee",
    category: "CROPPED TEE",
    price: 26.0,
    collection: "cropped-tees",
    image: "/cropped-tee-neutral-studio.png",
  },
  {
    slug: "oversized-basic-tee",
    name: "Oversized Basic Tee",
    category: "TEE",
    price: 24.0,
    collection: "t-shirts",
    image: "/studio-back-print-t-shirt.png",
  },
  {
    slug: "zip-up-hoodie",
    name: "Zip-Up Hoodie",
    category: "HOODIE",
    price: 62.0,
    collection: "hoodies",
    image: "/minimal-hoodie-back-print.png",
  },
  {
    slug: "cozy-hoodie",
    name: "Cozy Hoodie",
    category: "HOODIE",
    price: 55.0,
    collection: "hoodies",
    image: "/cozy-hoodie.png",
    badge: "Popular"
  },
  {
    slug: "cropped-tee-minimal",
    name: "Cropped Tee Minimal",
    category: "CROPPED TEE",
    price: 22.0,
    collection: "cropped-tees",
    image: "/cropped-tee-minimal.png",
  },
  {
    slug: "heavyweight-tee-neutral",
    name: "Heavyweight Tee Neutral",
    category: "TEE",
    price: 30.0,
    collection: "t-shirts",
    image: "/heavyweight-tee-neutral.png",
  },
  {
    slug: "sweatshirt-minimal",
    name: "Sweatshirt Minimal",
    category: "SWEATSHIRT",
    price: 45.0,
    collection: "sweatshirts",
    image: "/sweatshirt-minimal.png",
  },
  {
    slug: "t-shirt-neutral-studio",
    name: "T-Shirt Neutral Studio",
    category: "TEE",
    price: 26.0,
    collection: "t-shirts",
    image: "/t-shirt-neutral-studio.png",
  },
  {
    slug: "back-print-t-shirt",
    name: "Back Print T-Shirt",
    category: "TEE",
    price: 32.0,
    collection: "t-shirts",
    image: "/back-print-t-shirt.png",
    badge: "New"
  },
  // NEW PRODUCTS FROM PUBLIC FOLDER
  {
    slug: "baggy-denim-trousers",
    name: "Baggy Denim Trousers",
    category: "TROUSERS",
    price: 78.0,
    collection: "bottoms",
    image: "/baggy-denim-trousers.png",
    badge: "New"
  },
  {
    slug: "baseball-cap",
    name: "Baseball Cap",
    category: "ACCESSORY",
    price: 24.0,
    collection: "accessories",
    image: "/baseball-cap-neutral.png",
  },
  {
    slug: "beanie-neutral",
    name: "Cozy Beanie",
    category: "ACCESSORY",
    price: 18.0,
    collection: "accessories",
    image: "/beanie-neutral.png",
  },
  {
    slug: "beige-chino-pants",
    name: "Beige Chino Pants",
    category: "PANTS",
    price: 65.0,
    collection: "bottoms",
    image: "/beige-chino-pants.png",
  },
  {
    slug: "bomber-jacket",
    name: "Bomber Jacket",
    category: "JACKET",
    price: 95.0,
    collection: "outerwear",
    image: "/bomber-jacket-neutral.png",
    badge: "Popular"
  },
  {
    slug: "chino-pants-neutral",
    name: "Classic Chino Pants",
    category: "PANTS",
    price: 62.0,
    collection: "bottoms",
    image: "/chino-pants-neutral.png",
  },
  {
    slug: "khaki-shorts",
    name: "Khaki Shorts",
    category: "SHORTS",
    price: 38.0,
    collection: "bottoms",
    image: "/khaki-shorts-minimal.png",
  },
  {
    slug: "overshirt",
    name: "Relaxed Overshirt",
    category: "OVERSHIRT",
    price: 72.0,
    collection: "outerwear",
    image: "/overshirt.png",
  },
  {
    slug: "relaxed-linen-jacket",
    name: "Relaxed Linen Jacket",
    category: "JACKET",
    price: 88.0,
    collection: "outerwear",
    image: "/relaxed-linen-jacket.png",
    badge: "New"
  },
  {
    slug: "stylish-sneaker",
    name: "Stylish Sneaker",
    category: "SNEAKER",
    price: 125.0,
    collection: "accessories",
    image: "/stylish-sneaker.png",
    badge: "Bestseller"
  },
  {
    slug: "white-sneaker-minimal",
    name: "White Minimal Sneaker",
    category: "SNEAKER",
    price: 98.0,
    collection: "accessories",
    image: "/white-sneaker-minimal.png",
  }
]

