export type Product = {
  slug: string
  name: string
  category: "t-shirts" | "hoodies" | "sweatshirts" | "cropped-tees" | "bottoms" | "outerwear" | "accessories"
  subcategory?: string
  price: number
  image: string
  hoverImage?: string
  badge?: string
  description?: string
  sizes?: string[]
  colors?: string[]
  materials?: string[]
  care?: string
  sku?: string
  inStock?: boolean
  tags?: string[]
  seoTitle?: string
  metaDescription?: string
  featured?: boolean
  dateAdded?: string
}

export const products: Product[] = [
  {
    slug: "heavyweight-classic-tee",
    name: "Heavyweight Classic Tee",
    category: "t-shirts",
    subcategory: "classic-basics",
    price: 1299,
    image: "/basic-black-tee-back-print.png",
    hoverImage: "/t-shirt-neutral-studio.png",
    badge: "Bestseller",
    description: "Premium 240gsm cotton tee with a relaxed fit. Soft hand-feel and reinforced neckline for everyday wear.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Gray"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "oversized-graphic-hoodie",
    name: "Oversized Graphic Hoodie",
    category: "hoodies",
    subcategory: "pullover-hoodies",
    price: 2699,
    image: "/minimal-hoodie-back-print.png",
    hoverImage: "/cozy-hoodie.png",
    badge: "New",
    description: "Cozy oversized fit with brushed fleece interior. Minimal graphic print and double-stitched seams.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["80% Cotton, 20% Polyester"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "crewneck-sweatshirt",
    name: "Crewneck Sweatshirt",
    category: "sweatshirts",
    subcategory: "crewneck",
    price: 2299,
    image: "/minimal-sweatshirt-neutral.png",
    description: "Classic crewneck with ribbed collar and cuffs. Mid-weight loopback cotton.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "boxy-cropped-tee",
    name: "Boxy Cropped Tee",
    category: "cropped-tees",
    subcategory: "boxy-cropped",
    price: 1199,
    image: "/cropped-tee-neutral-studio.png",
    description: "Boxy silhouette with a modern cropped length. Silky-soft cotton modal blend.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Pink"],
    materials: ["95% Cotton, 5% Elastane"],
    care: "Machine wash cold, hang dry"
  },
  {
    slug: "oversized-basic-tee",
    name: "Oversized Basic Tee",
    category: "t-shirts",
    subcategory: "oversized-tees",
    price: 1099,
    image: "/studio-back-print-t-shirt.png",
    description: "Ultra-comfortable oversized tee with dropped shoulders and relaxed fit.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "zip-up-hoodie",
    name: "Zip-Up Hoodie",
    category: "hoodies",
    subcategory: "zip-up-hoodies",
    price: 2899,
    image: "/minimal-hoodie-back-print.png",
    description: "Versatile zip-up hoodie perfect for layering. Features kangaroo pocket and adjustable drawstring hood.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["80% Cotton, 20% Polyester"],
    care: "Machine wash cold, tumble dry low"
  },
  // Additional products with more variety
  {
    slug: "cozy-hoodie",
    name: "Cozy Hoodie",
    category: "hoodies",
    subcategory: "pullover-hoodies",
    price: 2599,
    image: "/cozy-hoodie.png",
    badge: "Popular",
    description: "Ultra-soft fleece interior with a relaxed fit. Perfect for lounging and casual outings.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "cropped-tee-minimal",
    name: "Cropped Tee Minimal",
    category: "cropped-tees",
    subcategory: "minimal-cropped",
    price: 999,
    image: "/cropped-tee-minimal.png",
    description: "Clean minimal design with a perfect cropped length. Essential for any wardrobe.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Beige"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, hang dry"
  },
  {
    slug: "heavyweight-tee-neutral",
    name: "Heavyweight Tee Neutral",
    category: "t-shirts",
    subcategory: "heavyweight-tees",
    price: 1399,
    image: "/heavyweight-tee-neutral.png",
    description: "Premium heavyweight cotton with a structured fit. Built to last through countless wears.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "sweatshirt-minimal",
    name: "Sweatshirt Minimal",
    category: "sweatshirts",
    subcategory: "minimal-sweatshirts",
    price: 2099,
    image: "/sweatshirt-minimal.png",
    description: "Clean minimal sweatshirt with a relaxed fit. Perfect for layering or wearing alone.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "t-shirt-neutral-studio",
    name: "T-Shirt Neutral Studio",
    category: "t-shirts",
    subcategory: "studio-tees",
    price: 1199,
    image: "/t-shirt-neutral-studio.png",
    description: "Studio-quality tee with a perfect fit. Designed for comfort and style.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low"
  },
  {
    slug: "back-print-t-shirt",
    name: "Back Print T-Shirt",
    category: "t-shirts",
    subcategory: "graphic-tees",
    price: 1499,
    image: "/back-print-t-shirt.png",
    badge: "New",
    description: "Statement back print tee with a relaxed fit. Make a statement with this eye-catching design.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Gray", "Navy"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, tumble dry low",
    sku: "TS-GR-001",
    inStock: true,
    tags: ["graphic", "statement", "cotton"],
    seoTitle: "Back Print T-Shirt - Graphic Tee - Premium Cotton",
    metaDescription: "Statement back print tee with relaxed fit. Eye-catching design in premium cotton. Shop graphic tees with free shipping!",
    featured: false,
    dateAdded: "2024-01-01"
  },
  // NEW PRODUCTS FROM PUBLIC FOLDER
  {
    slug: "baggy-denim-trousers",
    name: "Baggy Denim Trousers",
    category: "bottoms",
    subcategory: "trousers",
    price: 3599,
    image: "/baggy-denim-trousers.png",
    badge: "New",
    description: "Relaxed fit denim trousers with a modern baggy silhouette. Perfect for casual styling with oversized tees and hoodies.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Blue", "Black", "Light Blue"],
    materials: ["100% Cotton Denim"],
    care: "Machine wash cold, hang dry",
    sku: "BT-DN-001",
    inStock: true,
    tags: ["denim", "baggy", "casual", "trousers"],
    seoTitle: "Baggy Denim Trousers - Relaxed Fit - Premium Denim",
    metaDescription: "Modern baggy denim trousers with relaxed fit. Perfect for casual styling. Premium cotton denim construction.",
    featured: true,
    dateAdded: "2024-01-15"
  },
  {
    slug: "baseball-cap",
    name: "Baseball Cap",
    category: "accessories",
    subcategory: "hats",
    price: 1099,
    image: "/baseball-cap-neutral.png",
    description: "Classic baseball cap with structured crown and curved brim. Adjustable fit for all head sizes.",
    sizes: ["One Size"],
    colors: ["Black", "White", "Navy", "Gray"],
    materials: ["100% Cotton"],
    care: "Spot clean only",
    sku: "AC-CP-001",
    inStock: true,
    tags: ["cap", "baseball", "accessory", "casual"],
    seoTitle: "Baseball Cap - Classic Style - Adjustable Fit",
    metaDescription: "Classic baseball cap with structured crown. Adjustable fit, premium cotton construction. Complete your casual look.",
    featured: false,
    dateAdded: "2024-01-15"
  },
  {
    slug: "beanie-neutral",
    name: "Cozy Beanie",
    category: "accessories",
    subcategory: "beanies",
    price: 799,
    image: "/beanie-neutral.png",
    description: "Soft, stretchy beanie perfect for colder days. Ribbed knit construction with a comfortable fit.",
    sizes: ["One Size"],
    colors: ["Black", "White", "Gray", "Navy", "Beige"],
    materials: ["100% Acrylic"],
    care: "Machine wash cold, lay flat to dry",
    sku: "AC-BN-001",
    inStock: true,
    tags: ["beanie", "winter", "accessory", "cozy"],
    seoTitle: "Cozy Beanie - Soft Knit - Winter Accessory",
    metaDescription: "Soft, stretchy beanie for winter. Ribbed knit construction, comfortable fit. Stay warm in style.",
    featured: false,
    dateAdded: "2024-01-15"
  },
  {
    slug: "beige-chino-pants",
    name: "Beige Chino Pants",
    category: "bottoms",
    subcategory: "pants",
    price: 2999,
    image: "/beige-chino-pants.png",
    description: "Classic chino pants in a versatile beige color. Tailored fit with a modern silhouette, perfect for smart casual wear.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Beige", "Khaki", "Navy", "Black"],
    materials: ["100% Cotton Twill"],
    care: "Machine wash cold, hang dry",
    sku: "BT-CH-001",
    inStock: true,
    tags: ["chino", "pants", "smart-casual", "tailored"],
    seoTitle: "Beige Chino Pants - Tailored Fit - Smart Casual",
    metaDescription: "Classic chino pants in versatile beige. Tailored fit, cotton twill construction. Perfect for smart casual styling.",
    featured: true,
    dateAdded: "2024-01-15"
  },
  {
    slug: "bomber-jacket",
    name: "Bomber Jacket",
    category: "outerwear",
    subcategory: "jackets",
    price: 4399,
    image: "/bomber-jacket-neutral.png",
    badge: "Popular",
    description: "Classic bomber jacket with a modern fit. Features ribbed cuffs and hem, perfect for layering over tees and hoodies.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Olive", "Gray"],
    materials: ["100% Nylon Shell", "Polyester Lining"],
    care: "Machine wash cold, hang dry",
    sku: "OW-BJ-001",
    inStock: true,
    tags: ["bomber", "jacket", "outerwear", "casual"],
    seoTitle: "Bomber Jacket - Classic Style - Modern Fit",
    metaDescription: "Classic bomber jacket with modern fit. Ribbed cuffs and hem, perfect for layering. Nylon shell construction.",
    featured: true,
    dateAdded: "2024-01-15"
  },
  {
    slug: "chino-pants-neutral",
    name: "Classic Chino Pants",
    category: "bottoms",
    subcategory: "pants",
    price: 2899,
    image: "/chino-pants-neutral.png",
    description: "Essential chino pants with a comfortable fit. Versatile neutral color that pairs with everything in your wardrobe.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black", "Gray"],
    materials: ["100% Cotton Twill"],
    care: "Machine wash cold, hang dry",
    sku: "BT-CH-002",
    inStock: true,
    tags: ["chino", "pants", "neutral", "versatile"],
    seoTitle: "Classic Chino Pants - Neutral Color - Versatile Style",
    metaDescription: "Essential chino pants in neutral color. Comfortable fit, cotton twill construction. Versatile wardrobe staple.",
    featured: false,
    dateAdded: "2024-01-15"
  },
  {
    slug: "khaki-shorts",
    name: "Khaki Shorts",
    category: "bottoms",
    subcategory: "shorts",
    price: 1799,
    image: "/khaki-shorts-minimal.png",
    description: "Minimal khaki shorts with a relaxed fit. Perfect for summer styling with tees and tanks.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black", "White"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, hang dry",
    sku: "BT-SH-001",
    inStock: true,
    tags: ["shorts", "khaki", "summer", "minimal"],
    seoTitle: "Khaki Shorts - Minimal Style - Summer Essential",
    metaDescription: "Minimal khaki shorts with relaxed fit. Perfect for summer styling. Cotton construction, versatile color.",
    featured: false,
    dateAdded: "2024-01-15"
  },
  {
    slug: "overshirt",
    name: "Relaxed Overshirt",
    category: "outerwear",
    subcategory: "overshirts",
    price: 3299,
    image: "/overshirt.png",
    description: "Relaxed overshirt perfect for layering. Features a comfortable fit and versatile styling options.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Beige"],
    materials: ["100% Cotton"],
    care: "Machine wash cold, hang dry",
    sku: "OW-OS-001",
    inStock: true,
    tags: ["overshirt", "layering", "relaxed", "versatile"],
    seoTitle: "Relaxed Overshirt - Layering Piece - Versatile Style",
    metaDescription: "Relaxed overshirt perfect for layering. Comfortable fit, versatile styling. Cotton construction for all seasons.",
    featured: true,
    dateAdded: "2024-01-15"
  },
  {
    slug: "relaxed-linen-jacket",
    name: "Relaxed Linen Jacket",
    category: "outerwear",
    subcategory: "jackets",
    price: 4099,
    image: "/relaxed-linen-jacket.png",
    hoverImage: "/relaxed-linen-jacket-neutral-studio.png",
    badge: "New",
    description: "Breathable linen jacket with a relaxed silhouette. Perfect for warm weather and casual styling.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Beige", "White", "Navy", "Black"],
    materials: ["100% Linen"],
    care: "Dry clean only",
    sku: "OW-LJ-001",
    inStock: true,
    tags: ["linen", "jacket", "summer", "breathable"],
    seoTitle: "Relaxed Linen Jacket - Summer Essential - Breathable",
    metaDescription: "Breathable linen jacket with relaxed fit. Perfect for warm weather. 100% linen construction for comfort.",
    featured: true,
    dateAdded: "2024-01-15"
  },
  {
    slug: "stylish-sneaker",
    name: "Stylish Sneaker",
    category: "accessories",
    subcategory: "sneakers",
    price: 5799,
    image: "/stylish-sneaker.png",
    badge: "Bestseller",
    description: "Comfortable sneaker with a modern design. Perfect for everyday wear with any outfit.",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Navy", "Gray"],
    materials: ["Canvas Upper", "Rubber Sole"],
    care: "Spot clean with damp cloth",
    sku: "AC-SN-001",
    inStock: true,
    tags: ["sneaker", "shoes", "casual", "comfortable"],
    seoTitle: "Stylish Sneaker - Modern Design - Everyday Comfort",
    metaDescription: "Comfortable sneaker with modern design. Perfect for everyday wear. Canvas upper, rubber sole construction.",
    featured: true,
    dateAdded: "2024-01-15"
  },
  {
    slug: "white-sneaker-minimal",
    name: "White Minimal Sneaker",
    category: "accessories",
    subcategory: "sneakers",
    price: 4599,
    image: "/white-sneaker-minimal.png",
    description: "Clean minimal white sneaker with a timeless design. Versatile enough to pair with any outfit.",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Off-White", "Cream"],
    materials: ["Leather Upper", "Rubber Sole"],
    care: "Wipe clean with damp cloth",
    sku: "AC-SN-002",
    inStock: true,
    tags: ["sneaker", "white", "minimal", "versatile"],
    seoTitle: "White Minimal Sneaker - Timeless Design - Versatile Style",
    metaDescription: "Clean minimal white sneaker with timeless design. Versatile styling, leather upper. Perfect for any outfit.",
    featured: false,
    dateAdded: "2024-01-15"
  }
]
